id: P000560
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD90122
  title: ཁྲོ་ཆུ་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  volumes:
    3927f45703ea4ae280bb37c8d81442e2:
      image_group_id: I1PD90139
      title: Volume 1 of khro chu rdzong gi sa cha'i ming btus
      volume_number: 1
      total_pages: 162
      base_file: v001.txt
ebook_metadata:
  title: ཁྲོ་ཆུ་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  sku: P000560
  cover: cover.jpg
  layers:
  - pagination
