id: P000560
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:46:57.286994
source_metadata:
  id: bdr:W1PD90122
  title: ཁྲོ་ཆུ་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  volumes:
    3927f45703ea4ae280bb37c8d81442e2:
      image_group_id: I1PD90139
      title: Volume 1 of khro chu rdzong gi sa cha'i ming btus
      volume_number: 1
      total_pages: 162
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
